my_text = input()
print(my_text[2])
print(my_text[-2])
print(my_text[0:5])
x = len(my_text)
print(my_text[0:x - 2])
print(my_text[::2])
print(my_text[1::2])
print(my_text[::-1])
print(my_text[::-2])
print(x)
